In [1]:
import pandas as pd
import fastai

df = pd.read_csv('..\\data\\election_results\\1976-2020-senate.csv', 
                 skiprows=lambda x: 1<=x<=3048, # to start the year 2000 because party politics weird before then
                 # omit data after 2012 because don't have CF scores after that 
                 #skipfooter= 768, # last 2012 row is row2861, there are 3629 rows so need to skip the bottom 768 rows
                 encoding='latin1')

In [2]:
df = df[(df.special==False) & (df.writein==False) & (df.unofficial==False)]
df
df = df.loc[:,['year','state_po','candidate','candidatevotes','party_simplified','state']]
df
df = df[(df.party_simplified=='REPUBLICAN') | (df.party_simplified=='DEMOCRAT')]
df.head(10)

to_del = []
i = 0
while i<=df.shape[0]-3: # gives indexOB error when I try to go to the end. Works for now because I know (manually) that last one that needs to be deleted is within this range
    start = i # temp variable so we can get length of block later
    count = 0
    curr_state = df.iloc[i].state_po
    #from IPython.core.debugger import Pdb; Pdb().set_trace()
    while df.iloc[i].state_po==curr_state:
        count+=1
        i+=1
    if count == 2:
        pass#i+=1 # move onto next state
    else:
        print(start)
        to_del.extend(range(start,i)) # utilize non-inclusive upper bound because at this point, 
                                      # the next state has already been moved onto by incrementing i 
                                      # in the inner while loop above
        #i+=1 # AGH this is wrong cause if length less than 2, already moved onto next state
to_del
#df

# because .drop() uses an iterable of index LABELS, must do:
to_drop = [df.index[i] for i in to_del]
to_drop

elections = df.drop(to_drop)
elections

32
136
149
166

,year,state_po,candidate,candidatevotes,party_simplified,state
0,2016,AL,RON CRUMPTON,748709,DEMOCRAT,ALABAMA
1,2016,AL,RICHARD C. SHELBY,1335104,REPUBLICAN,ALABAMA
5,2016,AK,RAY METCALFE,36200,DEMOCRAT,ALASKA
8,2016,AK,LISA MURKOWSKI,138149,REPUBLICAN,ALASKA
11,2016,AZ,ANN KIRKPATRICK,1031245,DEMOCRAT,ARIZONA
...,...,...,...,...,...,...
562,2020,TX,"MARY ""MJ"" HEGAR",4888764,DEMOCRAT,TEXAS
566,2020,VA,MARK R. WARNER,2466500,DEMOCRAT,VIRGINIA
567,2020,VA,DANIEL M. GADE,1934199,REPUBLICAN,VIRGINIA
569,2020,WV,SHELLEY MOORE CAPITO,547454,REPUBLICAN,WEST VIRGINIA
570,2020,WV,PAULA JEAN SWEARENGIN,210309,DEMOCRAT,WEST VIRGINIA

In [3]:
elections.insert(3,'Dem_candidate',[None for x in range(elections.shape[0])])
elections.insert(4,'Repub_candidate',[None for x in range(elections.shape[0])])
elections.insert(5,'Dem_votes',[None for x in range(elections.shape[0])])
elections.insert(6,'Repub_votes',[None for x in range(elections.shape[0])])

In [4]:
i = 1 # because going to look at previous one
while i<=elections.shape[0]:
    if elections.iloc[i,8]=='DEMOCRAT': # party_simplified
        elections.iloc[i,3]=elections.iloc[i,2] # Dem_candidate, candidate
        elections.iloc[i,4]=elections.iloc[i-1,2] # Repub_candidate, candidate
        elections.iloc[i,5]=elections.iloc[i,7] # Dem_votes, candidatevotes
        elections.iloc[i,6]=elections.iloc[i-1,7] # Repub_votes, candidatevotes
    elif elections.iloc[i,8]=='REPUBLICAN':
        elections.iloc[i,3]=elections.iloc[i-1,2] # Dem_candidate, candidate
        elections.iloc[i,4]=elections.iloc[i,2] # Repub_candidate, candidate
        elections.iloc[i,5]=elections.iloc[i-1,7] # Dem_votes, candidatevotes
        elections.iloc[i,6]=elections.iloc[i,7] # Repub_votes, candidatevotes
    i+=2

In [5]:
elections = elections.iloc[1::2]

In [6]:
elections.insert(8,'Repub%of_two-party_vote', elections.Repub_votes/(elections.Dem_votes+elections.Repub_votes))
elections = elections.drop(['candidate','Dem_votes','Repub_votes','candidatevotes','party_simplified'], axis=1) # dropping in-place now is causing errors later

In [7]:
elections

,year,state_po,Dem_candidate,Repub_candidate,Repub%of_two-party_vote,state
1,2016,AL,RON CRUMPTON,RICHARD C. SHELBY,0.640702,ALABAMA
8,2016,AK,RAY METCALFE,LISA MURKOWSKI,0.79237,ALASKA
17,2016,AZ,ANN KIRKPATRICK,JOHN MCCAIN,0.568609,ARIZONA
23,2016,AR,CONNER ELDRIDGE,JOHN BOOZMAN,0.622993,ARKANSAS
26,2016,CA,KAMALA D. HARRIS,LORETTA SANCHEZ,0.383972,CALIFORNIA
...,...,...,...,...,...,...
545,2020,SC,JAIME HARRISON,LINDSEY GRAHAM,0.552079,SOUTH CAROLINA
550,2020,TN,MARQUITA BRADSHAW,BILL HAGERTY,0.638852,TENNESSEE
562,2020,TX,"MARY ""MJ"" HEGAR",JOHN CORNYN,0.549495,TEXAS
567,2020,VA,MARK R. WARNER,DANIEL M. GADE,0.439521,VIRGINIA
570,2020,WV,PAULA JEAN SWEARENGIN,SHELLEY MOORE CAPITO,0.722461,WEST VIRGINIA

<font size = 10>adding CF score equivalents</font>

CF scores are not available for candidates after 2012, so I will use the relationship between DW Nominate and CF Scores to calculate and approximate CF scores for incumbents (since having a DW Nominate score requires having a voting record) and use fast.ai's FillMissing for nonincumbents or names that otherwise can't find an associated score

In [8]:
# what 'Mapping the Ideological Marketplace' says about CF-DW Nominate relationship: 
# it looks like, from the graphs, cf score ~ dw nom * 2

In [9]:
# building dataset of DW nom scores
dws = pd.read_csv('..\\data\\candidate_ideology\\S116_members.csv') # for 2020 (2019-2021 congress session)

In [10]:
dws

,congress,chamber,icpsr,state_icpsr,district_code,state_abbrev,party_code,occupancy,last_means,bioname,...,died,nominate_dim1,nominate_dim2,nominate_log_likelihood,nominate_geo_mean_probability,nominate_number_of_votes,nominate_number_of_errors,conditional,nokken_poole_dim1,nokken_poole_dim2
0,116,President,99912,99,0.0,USA,200,0.0,0.0,"TRUMP, Donald John",...,NaN,0.403,0.162,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,116,Senate,41705,41,0.0,AL,100,NaN,NaN,"JONES, Gordon Douglas (Doug)",...,NaN,-0.088,0.187,-80.32594,0.88065,632.0,33.0,NaN,-0.081,0.234
2,116,Senate,94659,41,0.0,AL,200,NaN,NaN,"SHELBY, Richard C.",...,NaN,0.448,0.575,-46.01121,0.93295,663.0,27.0,NaN,0.437,0.219
3,116,Senate,40300,81,0.0,AK,200,NaN,NaN,"MURKOWSKI, Lisa",...,NaN,0.210,-0.302,-47.61779,0.92641,623.0,11.0,NaN,0.283,-0.424
4,116,Senate,41500,81,0.0,AK,200,NaN,NaN,"SULLIVAN, Daniel Scott",...,NaN,0.480,0.063,-53.40271,0.92101,649.0,25.0,NaN,0.510,-0.040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,116,Senate,40915,56,0.0,WV,100,NaN,NaN,"MANCHIN, Joe, III",...,NaN,-0.058,0.420,-70.59255,0.89783,655.0,19.0,NaN,-0.052,0.388
99,116,Senate,29940,25,0.0,WI,100,NaN,NaN,"BALDWIN, Tammy",...,NaN,-0.493,-0.136,-132.31357,0.81982,666.0,65.0,NaN,-0.396,-0.001
100,116,Senate,41111,25,0.0,WI,200,NaN,NaN,"JOHNSON, Ron",...,NaN,0.617,-0.182,-46.18103,0.93070,643.0,24.0,NaN,0.610,0.017
101,116,Senate,40707,68,0.0,WY,200,NaN,NaN,"BARRASSO, John A.",...,NaN,0.536,0.210,-31.02986,0.95461,668.0,15.0,NaN,0.602,0.323
102,116,Senate,49706,68,0.0,WY,200,NaN,NaN,"ENZI, Michael B.",...,2021.0,0.545,0.199,-42.60100,0.93551,639.0,16.0,NaN,0.587,0.414

In [11]:
dws = dws.loc[:,['congress','bioname','nominate_dim1']] # which dim to use?

In [13]:
dws2018 = pd.read_csv('..\\data\\candidate_ideology\\S115_members.csv')
dws2018 = dws2018.loc[:,['congress','bioname','nominate_dim1']]
dws2018

     congress                                    bioname  nominate_dim1
0         115                         TRUMP, Donald John          0.403
1         115              STRANGE, Luther  Johnson, III          0.560
2         115               JONES, Gordon Douglas (Doug)         -0.088
3         115  SESSIONS, Jefferson Beauregard III (Jeff)          0.549
4         115                         SHELBY, Richard C.          0.448
..        ...                                        ...            ...
101       115                          MANCHIN, Joe, III         -0.058
102       115                             BALDWIN, Tammy         -0.493
103       115                               JOHNSON, Ron          0.617
104       115                          BARRASSO, John A.          0.536
105       115                           ENZI, Michael B.          0.545

[106 rows x 3 columns]

In [15]:
dws2016 = pd.read_csv('..\\data\\candidate_ideology\\S114_members.csv')
dws2016 = dws2016.loc[:,['congress','bioname','nominate_dim1']]
dws2016

     congress                                    bioname  nominate_dim1
0         114                              OBAMA, Barack         -0.358
1         114  SESSIONS, Jefferson Beauregard III (Jeff)          0.549
2         114                         SHELBY, Richard C.          0.448
3         114                            MURKOWSKI, Lisa          0.210
4         114                     SULLIVAN, Daniel Scott          0.480
..        ...                                        ...            ...
96        114                          MANCHIN, Joe, III         -0.058
97        114                             BALDWIN, Tammy         -0.493
98        114                               JOHNSON, Ron          0.617
99        114                          BARRASSO, John A.          0.536
100       114                           ENZI, Michael B.          0.545

[101 rows x 3 columns]

In [16]:
dfs = [dws2016,dws2018,dws]
ideologies = pd.concat(dfs)
ideologies

     congress                                    bioname  nominate_dim1
0         114                              OBAMA, Barack         -0.358
1         114  SESSIONS, Jefferson Beauregard III (Jeff)          0.549
2         114                         SHELBY, Richard C.          0.448
3         114                            MURKOWSKI, Lisa          0.210
4         114                     SULLIVAN, Daniel Scott          0.480
..        ...                                        ...            ...
98        116                          MANCHIN, Joe, III         -0.058
99        116                             BALDWIN, Tammy         -0.493
100       116                               JOHNSON, Ron          0.617
101       116                          BARRASSO, John A.          0.536
102       116                           ENZI, Michael B.          0.545

[310 rows x 3 columns]

In [ ]:
d = {114:2016, 115:2018, 116: 2020} 
ideologies['congress'].map(d)